/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as BarberIndexRouteImport } from './routes/barber/index'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerServicesRouteImport } from './routes/owner/services'
import { Route as OwnerReportsRouteImport } from './routes/owner/reports'
import { Route as OwnerProductsRouteImport } from './routes/owner/products'
import { Route as OwnerFinancialRouteImport } from './routes/owner/financial'
import { Route as OwnerEmployeesRouteImport } from './routes/owner/employees'
import { Route as OwnerCustomersRouteImport } from './routes/owner/customers'
import { Route as OwnerAppointmentsRouteImport } from './routes/owner/appointments'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as ClientHistoryRouteImport } from './routes/client/history'
import { Route as ClientBookRouteImport } from './routes/client/book'
import { Route as BarberScheduleRouteImport } from './routes/barber/schedule'
import { Route as BarberRevenueRouteImport } from './routes/barber/revenue'
import { Route as BarberProfileRouteImport } from './routes/barber/profile'
import { Route as BarberHistoryRouteImport } from './routes/barber/history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberIndexRoute = BarberIndexRouteImport.update({
  id: '/barber/',
  path: '/barber/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/owner/services',
  path: '/owner/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/owner/products',
  path: '/owner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerFinancialRoute = OwnerFinancialRouteImport.update({
  id: '/owner/financial',
  path: '/owner/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEmployeesRoute = OwnerEmployeesRouteImport.update({
  id: '/owner/employees',
  path: '/owner/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCustomersRoute = OwnerCustomersRouteImport.update({
  id: '/owner/customers',
  path: '/owner/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAppointmentsRoute = OwnerAppointmentsRouteImport.update({
  id: '/owner/appointments',
  path: '/owner/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHistoryRoute = ClientHistoryRouteImport.update({
  id: '/client/history',
  path: '/client/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBookRoute = ClientBookRouteImport.update({
  id: '/client/book',
  path: '/client/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberScheduleRoute = BarberScheduleRouteImport.update({
  id: '/barber/schedule',
  path: '/barber/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRevenueRoute = BarberRevenueRouteImport.update({
  id: '/barber/revenue',
  path: '/barber/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberProfileRoute = BarberProfileRouteImport.update({
  id: '/barber/profile',
  path: '/barber/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberHistoryRoute = BarberHistoryRouteImport.update({
  id: '/barber/history',
  path: '/barber/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barber/history': typeof BarberHistoryRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/revenue': typeof BarberRevenueRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/client/book': typeof ClientBookRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/owner/appointments': typeof OwnerAppointmentsRoute
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/employees': typeof OwnerEmployeesRoute
  '/owner/financial': typeof OwnerFinancialRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/barber/': typeof BarberIndexRoute
  '/client/': typeof ClientIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barber/history': typeof BarberHistoryRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/revenue': typeof BarberRevenueRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/client/book': typeof ClientBookRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/owner/appointments': typeof OwnerAppointmentsRoute
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/employees': typeof OwnerEmployeesRoute
  '/owner/financial': typeof OwnerFinancialRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/barber': typeof BarberIndexRoute
  '/client': typeof ClientIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barber/history': typeof BarberHistoryRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/revenue': typeof BarberRevenueRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/client/book': typeof ClientBookRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/owner/appointments': typeof OwnerAppointmentsRoute
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/employees': typeof OwnerEmployeesRoute
  '/owner/financial': typeof OwnerFinancialRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/barber/': typeof BarberIndexRoute
  '/client/': typeof ClientIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/barber/history'
    | '/barber/profile'
    | '/barber/revenue'
    | '/barber/schedule'
    | '/client/book'
    | '/client/history'
    | '/client/profile'
    | '/owner/appointments'
    | '/owner/customers'
    | '/owner/employees'
    | '/owner/financial'
    | '/owner/products'
    | '/owner/reports'
    | '/owner/services'
    | '/owner/settings'
    | '/barber/'
    | '/client/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/barber/history'
    | '/barber/profile'
    | '/barber/revenue'
    | '/barber/schedule'
    | '/client/book'
    | '/client/history'
    | '/client/profile'
    | '/owner/appointments'
    | '/owner/customers'
    | '/owner/employees'
    | '/owner/financial'
    | '/owner/products'
    | '/owner/reports'
    | '/owner/services'
    | '/owner/settings'
    | '/barber'
    | '/client'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/barber/history'
    | '/barber/profile'
    | '/barber/revenue'
    | '/barber/schedule'
    | '/client/book'
    | '/client/history'
    | '/client/profile'
    | '/owner/appointments'
    | '/owner/customers'
    | '/owner/employees'
    | '/owner/financial'
    | '/owner/products'
    | '/owner/reports'
    | '/owner/services'
    | '/owner/settings'
    | '/barber/'
    | '/client/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BarberHistoryRoute: typeof BarberHistoryRoute
  BarberProfileRoute: typeof BarberProfileRoute
  BarberRevenueRoute: typeof BarberRevenueRoute
  BarberScheduleRoute: typeof BarberScheduleRoute
  ClientBookRoute: typeof ClientBookRoute
  ClientHistoryRoute: typeof ClientHistoryRoute
  ClientProfileRoute: typeof ClientProfileRoute
  OwnerAppointmentsRoute: typeof OwnerAppointmentsRoute
  OwnerCustomersRoute: typeof OwnerCustomersRoute
  OwnerEmployeesRoute: typeof OwnerEmployeesRoute
  OwnerFinancialRoute: typeof OwnerFinancialRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  BarberIndexRoute: typeof BarberIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/': {
      id: '/barber/'
      path: '/barber'
      fullPath: '/barber/'
      preLoaderRoute: typeof BarberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/owner/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/owner/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/financial': {
      id: '/owner/financial'
      path: '/owner/financial'
      fullPath: '/owner/financial'
      preLoaderRoute: typeof OwnerFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/employees': {
      id: '/owner/employees'
      path: '/owner/employees'
      fullPath: '/owner/employees'
      preLoaderRoute: typeof OwnerEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/customers': {
      id: '/owner/customers'
      path: '/owner/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof OwnerCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/appointments': {
      id: '/owner/appointments'
      path: '/owner/appointments'
      fullPath: '/owner/appointments'
      preLoaderRoute: typeof OwnerAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/history': {
      id: '/client/history'
      path: '/client/history'
      fullPath: '/client/history'
      preLoaderRoute: typeof ClientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/book': {
      id: '/client/book'
      path: '/client/book'
      fullPath: '/client/book'
      preLoaderRoute: typeof ClientBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/schedule': {
      id: '/barber/schedule'
      path: '/barber/schedule'
      fullPath: '/barber/schedule'
      preLoaderRoute: typeof BarberScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/revenue': {
      id: '/barber/revenue'
      path: '/barber/revenue'
      fullPath: '/barber/revenue'
      preLoaderRoute: typeof BarberRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/profile': {
      id: '/barber/profile'
      path: '/barber/profile'
      fullPath: '/barber/profile'
      preLoaderRoute: typeof BarberProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/history': {
      id: '/barber/history'
      path: '/barber/history'
      fullPath: '/barber/history'
      preLoaderRoute: typeof BarberHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BarberHistoryRoute: BarberHistoryRoute,
  BarberProfileRoute: BarberProfileRoute,
  BarberRevenueRoute: BarberRevenueRoute,
  BarberScheduleRoute: BarberScheduleRoute,
  ClientBookRoute: ClientBookRoute,
  ClientHistoryRoute: ClientHistoryRoute,
  ClientProfileRoute: ClientProfileRoute,
  OwnerAppointmentsRoute: OwnerAppointmentsRoute,
  OwnerCustomersRoute: OwnerCustomersRoute,
  OwnerEmployeesRoute: OwnerEmployeesRoute,
  OwnerFinancialRoute: OwnerFinancialRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  BarberIndexRoute: BarberIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
